# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook.proto',
  package='addressbook',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61\x64\x64ressbook.proto\x12\x0b\x61\x64\x64ressbook\"*\n\x07Message\x12\x0e\n\x06\x66ormat\x18\x01 \x02(\t\x12\x0f\n\x07payload\x18\x02 \x02(\t2\x9e\x02\n\nRPCService\x12\x46\n\x16GetPersonByPhoneNumber\x12\x14.addressbook.Message\x1a\x14.addressbook.Message\"\x00\x12<\n\nEditPeople\x12\x14.addressbook.Message\x1a\x14.addressbook.Message\"\x00(\x01\x12G\n\x15ListPeopleByPhoneType\x12\x14.addressbook.Message\x1a\x14.addressbook.Message\"\x00\x30\x01\x12\x41\n\rGetPeopleById\x12\x14.addressbook.Message\x1a\x14.addressbook.Message\"\x00(\x01\x30\x01'
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='addressbook.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='addressbook.Message.format', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='addressbook.Message.payload', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'addressbook_pb2'
  # @@protoc_insertion_point(class_scope:addressbook.Message)
  })
_sym_db.RegisterMessage(Message)



_RPCSERVICE = _descriptor.ServiceDescriptor(
  name='RPCService',
  full_name='addressbook.RPCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=365,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPersonByPhoneNumber',
    full_name='addressbook.RPCService.GetPersonByPhoneNumber',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditPeople',
    full_name='addressbook.RPCService.EditPeople',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListPeopleByPhoneType',
    full_name='addressbook.RPCService.ListPeopleByPhoneType',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPeopleById',
    full_name='addressbook.RPCService.GetPeopleById',
    index=3,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPCSERVICE)

DESCRIPTOR.services_by_name['RPCService'] = _RPCSERVICE

# @@protoc_insertion_point(module_scope)
